version: "3"
services:
  client:
    container_name: dhyana-client
    build: ./client
    restart: always
    ports:
      - "8080:8080"
    stdin_open: true
    volumes:
      - ./client:/usr/src/client
      - /usr/src/client/node_modules/

  api:
    container_name: dhyana-api
    build: ./api
    ports:
      - "3000:3000"
    networks:
      - dbapi
    environment:
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_USER: "postgres"

    command: ["./wait-for-it.sh", "db:5432", "--", "npm", "start"]
    stdin_open: true
    tty: true
    volumes:
      - ./api:/usr/src/api
      - /usr/src/api/node_modules/

  db:
    image: "postgres:latest"
    networks:
      - dbapi
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dhyana
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust

networks:
  dbapi:
